agentName:  agent001
namespace:  agent001
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com/agent001
giteaBaseUrl: :443/gitea/giteaAdmin

imageBase: :443/gitea/giteaadmin

envs:
  - name: dev
    depends: None
    cluster: cnoe-ref-impl