agentName: agent001
envName: dev
agentRuntimeName: agent001_dev
imageRepo: 229560443702.dkr.ecr.us-west-2.amazonaws.com
tag: b97bb6d853c8971eb483224679455e7659a31087
roleArn: arn:aws:iam::229560443702:role/service-role/AmazonBedrockAgentCoreRuntimeDefaultServiceRole

environmentVariables:
  TENANT_SECRETS_PATH: "tenant01/agent001_dev"
  # REGION: "us-west-2"
